Add protocol support for DNS
facebookincubator/fbender pull request #6
Opened 2018-10-14 02:45 UTC by Seanstoppable

Allow testing of DNS using UDP or TCP.
Default to UDP (current/normal behavior)

2018-10-14 09:00 UTC, pallotron requested changes
Thanks for your PR!
Can you please post a gist/pastebin in the commit message or in this discussion showing the intended behavior working?

2018-10-14 09:03 UTC, pallotron requested changes

2018-10-14 09:03 UTC, pallotron commented on tester/dns/tester.go
>  // Tester is a load tester for DHCPv6
whoops, there is a typo here :D it should be DNS :) do you mind changing it while you are at it?

2018-10-14 14:22 UTC, Seanstoppable commented on tester/dns/tester.go
>  // Tester is a load tester for DHCPv6
No problem!

2018-10-14 14:27 UTC, Seanstoppable commented
@pallotron 
Using `--protocol tcp` I receive errors like the following:
```
{"elapsed":7096556621,"end":1539526762992974999,"error":"read tcp 127.0.0.1:60004-\u003e127.0.0.1:53: read: connection reset by peer","level":"warning","msg":"Fail","response":null,"start":1539526755896418378,"test":2000,"time":"2018-10-14T09:19:22-05:00"}
```

Using `--protocol udp` or no option, I receive errors like the following:
```
{"elapsed":20019884796,"end":1539527128271874012,"error":"read udp 127.0.0.1:55587-\u003e127.0.0.1:53: i/o timeout","level":"warning","msg":"Fail","response":null,"start":1539527108251989216,"test":2000,"time":"2018-10-14T09:25:28-05:00"}
```

2018-10-14 20:23 UTC, pallotron commented
you should not receive any error. Looking at the errors:

```
127.0.0.1:53: read: connection reset by peer 
```
```
127.0.0.1:53: i/o timeout"
```
It looks like you don't have any DNS server running on port localhost:53? 
do you have a DNS server running on 127.0.0.1:53? :D
How are you testing this? :)

2018-10-14 21:39 UTC, earlgreyz commented on cmd/dns/cmd.go
> +		"protocol", "p", "udp", "protocol to use for DNS queries. Can be tcp or udp (default udp)")
text "default: udp" will be added automatically while generating help messages by cobra, so It can be omitted

2018-10-15 15:30 UTC, Seanstoppable commented
@pallotron Sorry, let me expand
I don't get constant errors, but at sufficiently high loads one would get errors. The error messages are really just illustrating that with one option, we are using TCP and with another option, we are using UDP.

2018-10-15 16:53 UTC, pallotron commented
@Seanstoppable alright, understood now :)

2018-10-15 19:36 UTC, pallotron commented
there were some issues with our TravisCI integration, do you mind submitting another trivial commit to check if it is working?
Alternatively we can try closing and reopening the PR to see if TravisCI is triggered :)

2018-10-15 19:46 UTC, insomniacslk commented
> do you mind submitting another trivial commit to check if it is working?

Can also use `git commit --allow-empty`, that will trigger the build and won't require any change in the code

2018-10-16 07:54 UTC, pallotron commented
this looks good to me, I will merge this later on my day if @earlgreyz is happy with the code :)

2018-10-16 07:55 UTC, earlgreyz approved these changes
LGTM

2018-10-16 08:58 UTC, closed without merging